FROM node:12.16.1-alpine As builder

WORKDIR /usr/src/app

COPY package.json package-lock.json ./

RUN npm install

COPY . .

RUN npm install -g @angular/cli

RUN ng build --configuration production --output-path=/dist

RUN npm run build --prod --output-path="dist/"

FROM nginx:alpine

COPY --from=builder /usr/src/app/dist/ /usr/share/nginx/html

CMD ["/bin/sh", "-c", "sed -i 's/listen  .*/listen $PORT;/g' /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"]